### ISSUE TITLE
Refactoring decorators

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#178]
The decorators being in httomolibgpu library pose few problems:
- multidata I/O needs to be dealt with in httomo (temporary solution)
- Adding methods directly requires either creating decorators  for a new module or creating a library file. Creating wrappers in httomolibgpu to add a new library goes against the idea of adding backends **directly** 

It has been decided to:

-  place all information about the backends in the local to httomo library file (similar to [tomopy](https://github.com/DiamondLightSource/httomo/blob/main/httomo/methods_database/packages/external/tomopy/1.14/tomopy.yaml) library) and remove decorators from httomolibgpu 
- initiate a new syntax that would direct a **single** memory estimation function, for instance
```
paganin: 
  memory: 
    arrays: [tomo, tomo]
    multipliers: [2, 1]
    methods: [none, Fourier_real]
```
or
```
normalize: 
  memory: 
    arrays: [tomo, flats, darks]
    multipliers: [2, 1.1, 1.1]
```
- Move MemoryHook tests into Httomo
