### ISSUE TITLE
Creating tests for methods in httomolib/tomopy

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#2]
Create tests for the methods that are available in httomolib/tomopy. This is a bit tricky one, here are my thoughts about it,  please feel free to add yours @namannimmo10 @yousefmoazzam 

1. In the _tests_ folder we create a YAML file which would be of the following structure:
```
- tomopy.misc.corr:
   median_filter2d:
   median_filter3d:
   ...
- tomopy.prep.stripe:
   remove_stripe_fw:
   remove_all_stripes:
   ...
```
The the file we enlist methods explicitly that we would like to test. If a new method added it should be added into the YAML test file. 
2. The YAML generator should loop through the tests configuration file and generate the corresponding YAML files for the runner for each method. 
3.  We write a general test script that would go through the methods given in the file and run/ test each of them in a loop. The data needs to be loaded once potentially. 
4. This script needs to run a runner in the same way as we run httomo task_runner
5.  Tests should check for:
* The generated YAML is correct
* The runner runs, the I/O work as expected
* The answer is valid, the method does work correctly
* may be something else...
