### ISSUE TITLE
Incorrect slicing applied to darks in `get_darks_flats()`

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/HTTomo#35]
With the data `/dls/i12/data/2022/nt33730-1/rawdata/119647.nxs`, when applying a minimal pipeline which involves previewing like the following
```
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: entry1/tomo_entry/data/data
      image_key_path: entry1/tomo_entry/instrument/detector/image_key
      dimension: 1
      preview:
        - start:
          stop: 220
        - start:
          stop: 128
        - start:
          stop: 160
      pad: 0
- tomopy.prep.normalize:
    normalize:
      data_in: tomo
      data_out: tomo
      cutoff: null
```

the following error occurs:
```
ValueError: operands could not be broadcast together with shapes (150,128,160) (128,2560)
```

As Lucas pointed out, the `slice` objects in `slice_list` in the following line: https://github.com/DiamondLightSource/HTTomo/blob/4fe3c779a4337a7bdaa0c97cefe2870abe5d79ca/src/httomo/data/hdf/_utils/load.py#L423 are being applied incorrectly (ie, putting each `slice` object in its own separate pair of square brackets, rather than putting all `slice` objects separated by commas within one pair of square brackets).
