### ISSUE TITLE
Simplify `memory_gpu` field in methods database entry structure

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#358]
## Current structure

YAML
```yaml
memory_gpu: 
   - datasets: [tomo] 
   - multipliers: [2.1] 
   - methods: [direct] 
```

where the value of the `memory_gpu` field parses into the following python:
```python
[
  {"datasets": ["tomo"]},
  {"multipliers": [2.1]},
  {"methods": ["direct"]},
]
```

## Goal for simplified structure

YAML
```yaml
memory_gpu: 
  datasets: "tomo"
  multipliers: 2.1
  methods: "direct"
```

where the value of the `memory_gpu` field parses into the following python:
```python
{
  "datasets": "tomo",
  "multipliers": 2.1,
  "methods": "direct",
}
```

- [ ] #356
- [ ] #357
