### ISSUE TITLE
memory issue with FBP followed by median filter

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#368]
Possibly related to #365, but also can be a stand-alone issue. The following combination leads to OOM Cuda error for FBP on IFFT step (tried on 40Gb dataset on hopper). 
```
FBP (httomolibgpu)
median_filter (httomolibgpu)
```
It happens mid-way through the blocks which might point that the memory with the  `median_filter` step is somehow accumulated in block-iterations?

```
    FBP (httomolibgpu)
    median_filter (httomolibgpu)
     0%|          | 0/6 [00:00<?, ?block/s]
    17%|#6        | 1/6 [00:19<01:35, 19.07s/block]
    33%|###3      | 2/6 [00:36<01:11, 17.91s/block]
    50%|#####     | 3/6 [00:53<00:52, 17.54s/block]
```

**Comment by dkazanc** [comment]
Sorry missed the important part, the result of the reconstruction is not to be saved, e.g.: 
```
- method: FBP
  module_path: httomolibgpu.recon.algorithm
  parameters:
    filter_freq_cutoff: 0.6
    center: ${{centering.side_outputs.centre_of_rotation}}
    recon_size: null
    recon_mask_radius: null
  save_result: false
- method: median_filter
  module_path: httomolibgpu.misc.corr
  parameters:
    kernel_size: 3
    dif: 0.0
    axis: auto 
```
