### ISSUE TITLE
introduction of the pattern parameter

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#41]
As discussed earlier with @yousefmoazzam, we need a `pattern` parameter (e.g. projection, sinogram, volume) that would define how the data being passed into the module.  This would also define the position of the reslicing procedure in the pipeline list. The number of reslicing operations needs to be minimised to accelerate the process. The means that the order of the methods is important in the process list and should be checked before every run. 

So far what could be done:  
1. The run terminated and the warning raised if there is an unnecessary switches from projection slicing to sinogram and back. Therefore we need to check the associated patterns of all modules present in the pipeline. I guess we could divide into 3 patterns so far: sinogram, volume, projection. The tricky bit here is that volume pattern doesn't care if the data is in sinogram or projection pattern. 
2. With the `--force` flag attached to the runner, the run will be executed despite multiple reslicing operations needed.

**Comment by yousefmoazzam** [comment]
A first attempt at implementing the `pattern` functionality is in 9acd655.

I'm sure there will be a few things I've missed to fix still, but currently, reslicing using the pattern functionality is able to handle the case in #42, and can run a basic GPU pipeline like the following:
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: entry1/tomo_entry/data/data
      image_key_path: entry1/tomo_entry/instrument/detector/image_key
      dimension: 1
      preview:
        - 
        - start: 900
          stop: 905
        - 
      pad: 0
- httomolib.prep.normalize:
    normalize_cupy:
      data_in: tomo
      data_out: tomo
      cutoff: 10.0
      minus_log: true
- httomolib.recon.rotation:
    find_center_vo_cupy:
      data_in: tomo
      data_out: cor
      ind: mid
      smin: -50
      smax: 50
      srad: 6
      step: 0.25
      ratio: 0.5
      drop: 20
- httomolib.recon.algorithm:
    reconstruct_tomopy:
      data_in: tomo
      data_out: tomo
      center: null
      algorithm: FBP_CUDA
- httomolib.misc.images:
    save_to_images:
      data_in: tomo
      subfolder_name: images
      axis: 0
      file_format: tif
      bits: 8
      perc_range_min: 0.0
      perc_range_max: 100.0
      jpeg_quality: 95

```
without error (both a serial run, and parallel run with MPI).
