### ISSUE TITLE
CoR before normalisation issue

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#42]
the runner fails when the CoR function is placed before normalisation.  The error is along those lines:
`ValueError: operands could not be broadcast together with shapes (1801, 7, 2560) (1, 20, 2560)`

**Comment by yousefmoazzam** [comment]
The following minimal pipeline
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: entry1/tomo_entry/data/data
      image_key_path: entry1/tomo_entry/instrument/detector/image_key
      dimension: 1
      preview:
        - 
        - start: 900
          stop: 903
        - 
      pad: 0
- httomolib.recon.rotation:
    find_center_vo_cupy:
      data_in: tomo
      data_out: cor
      ind: mid
      smin: -50
      smax: 50
      srad: 6
      step: 0.25
      ratio: 0.5
      drop: 20      
- httomolib.prep.normalize:
    normalize_cupy:
      data_in: tomo
      data_out: tomo
      cutoff: 10.0
      minus_log: true
```
(and its CPU equivalent using methods from tomopy) was failing with a broadcast error when given the input data `/dls/i12/data/2022/nt33730-1/rawdata/119647.nxs` and when running with MPI.

The root cause of this bug appears to be related to the reslicing being done in the runner when a centering method is present in the pipeline.

Currently, the "rules" for when and when-not to reslice the data before applying the next method in the pipeline are rather hacky, see the following function: https://github.com/DiamondLightSource/httomo/blob/8fb5d5a95665859a1852475d06ad3e5066fb16a0/src/httomo/task_runner.py#L652-L689

What appears to be happening to cause this error when the order of methods is `loader -> centering -> normalization` is:
- data is loaded, being split between MPI processes along dimension 1 / projection dimension
- before centering, there's a need to reslice the data according to the rules in `_check_if_should_reslice()`
- data is resliced and split between MPI processes along dimension 2 / sinogram dimension
- centering is applied
- before normalization, there is no need to reslice the data according to the rules in `_check_if_should_reslice()`, so the data is still being read and split along dimension 2 / sinogram dim, because the same "setting" for how to slice the data that was done for the prior centering method has been left in place
- in normalization, the different MPI processes are thus handed data that is split along dim 2 / sinogram dim, causing the projection data to be split in dimension 2 / sinogram dimension / `detector_y` dimension, which results in the broadcast error previously mentioned

The proposed feature in #41 would allow the rules for reslicing to be more robust and would be a nice way to fix this bug, so hopefully this bug can be resolved by implementing that feature.
