### ISSUE TITLE
Intermediate datasets are incorrectly chunked

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#44]
If the following minimal pipeline is run:
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: entry1/tomo_entry/data/data
      image_key_path: entry1/tomo_entry/instrument/detector/image_key
      dimension: 1
      preview:
        - 
        - start: 900
          stop: 905
        - 
      pad: 0
- httomolib.recon.rotation:
    find_center_vo_cupy:
      data_in: tomo
      data_out: cor
      ind: mid
      smin: -50
      smax: 50
      srad: 6
      step: 0.25
      ratio: 0.5
      drop: 20   
```
with the data `/dls/i12/data/2022/nt33730-1/rawdata/119647.nxs`, then the intermediate dataset that is created before the centering method runs and passed to the centering method for processing is currently being chunked in the _projection_ dimensions (dim 1) as opposed to the _sinogram_ dimension (dim 2):
```bash
[twi18192@pc0074 HTTomo (gpurunner)]$ h5dump -d /data -H -p /scratch/twi18192/git-repos/HTTomo/outdata/25-01-2023_16_34_24_output/intermediate.h5
HDF5 "/scratch/twi18192/git-repos/HTTomo/outdata/25-01-2023_16_34_24_output/intermediate.h5" {
DATASET "/data" {
   DATATYPE  H5T_STD_U16LE
   DATASPACE  SIMPLE { ( 1801, 5, 2560 ) / ( 1801, 5, 2560 ) }
   STORAGE_LAYOUT {
      CHUNKED ( 1, 5, 2560 )
      SIZE 46105600
   }
```

This isn't the intended behaviour: one important motivation for the reslice step between certain methods is to have the data chunked in a way that is optimal for the next method to run. To be more optimal, the centering method is intended to get data that is chunked in the _sinogram_ dimension, but it is seemingly getting data that is chunked in the _projection_ dimension.

This is also an issue that is connected to #41, so this will be fixed alongside the introduction of that new feature.
