### ISSUE TITLE
Auto insertion of calculate_stats and rescale_to_int evaluation

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#452]
also related to #449 

Further thinking about the sequence of methods that lead to `save_to_images` method, e.g. in the "gpu-intense" pipeline:
```
- method: calculate_stats
  module_path: httomo.methods
  parameters: {}
  id: statistics
  side_outputs:
    glob_stats: glob_stats  
- method: rescale_to_int
  module_path: httomolibgpu.misc.rescale
  parameters:
    perc_range_min: 15.0
    perc_range_max: 85.0
    bits: 8
    glob_stats: ${{statistics.side_outputs.glob_stats}}
- method: save_to_images
  module_path: httomolib.misc.images
  parameters:
    subfolder_name: images
    axis: auto
    file_format: tif
    bits: 8
    perc_range_min: 0.0
    perc_range_max: 95.0
    jpeg_quality: 95
    glob_stats: ${{statistics.side_outputs.glob_stats}} 
```

1. I see that the calculation of statistics should be probably automated as it usually gets applied before the image saver and the data needs to be transferred to CPU anyway. I suggest we make by default an insertion method, i.e. if there is `save_to_images` in the pipeline, then `calculate_stats` must be auto-inserted. This is also follows the idea how the [template](https://diamondlightsource.github.io/httomo-backends/api/httomolib.misc.images.html) for image saver is actually distributed, already with the reference to it `glob_stats: ${{statistics.side_outputs.glob_stats}}`. This also makes things simpler for users. 
2. Secondly the `rescale_to_int` method which is a GPU only method currently. After statistics calculation the data needs to be transferred to the GPU again, right? I'm not 100% sure but I think that the GPU data will be transferred for calculation of statistics and GPU memory references will be destroyed, meaning that `rescale_to_int` will transfer the data to GPU again, before it will be transferred back to CPU for `save_to_images`. a) I'm not sure how optimal that is b) `rescale_to_int` differs slightly from more time consuming implementation in `save_to_images` using  `exposure.rescale_intensity` function.   But the default parameters are different for those methods, yet they do the same rescaling operation, quite confusing! 

Overall I think this is all pretty confusing even for us not to mention the users than need to make sense of what exactly is going on and add 2 additional templates before `save_to_images`. 

My suggestion here is 1) automate auto-insertion of `calculate_stats` before `save_to_images`. 2) decide what to do with `rescale_to_int`, I sense that the CPU implementation might be not significantly slower that GPU after all those transfers, i.e. we need CPU implementation of that method to benchmark at least. 3) auto insert #449  it and switch the rescale off in  `save_to_images`, which now can be done with that [PR](https://github.com/DiamondLightSource/httomolib/pull/17) 4) with #449 the default parameters must be populated from `save_to_images`. 

However, the bottomline here, if `rescale_to_int` is a CPU method, then it should be a part of `save_to_images` and we need to remove it to avoid further confusion. I appreciate the existence of the GPU kernel but I have strong doubts about the effectiveness of such method in the current setting.
