### ISSUE TITLE
GPU memory allocation issues when reslices occur during MPI runs

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#49]
Due to limited debugging capabilites for MPI runs it's hard to have anything concrete unfortunately...

However, when developing on the `improve-loader-params` branch, it was noticed when running the following YAML pipeline with 2 processes under MPI (note the ordering of centering before normalisation, which will cause 3 reslice operations rather than just 1):
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: entry1/tomo_entry/data/data
      image_key_path: entry1/tomo_entry/instrument/detector/image_key
      dimension: 1
      preview:
        - 
        - start: 900
          stop: 905
        - 
      pad: 0
- httomolib.recon.rotation:
    find_center_vo_cupy:
      data_in: tomo
      data_out: cor
      ind: mid
      smin: -50
      smax: 50
      srad: 6
      step: 0.25
      ratio: 0.5
      drop: 20      
- httomolib.prep.normalize:
    normalize_cupy:
      data_in: tomo
      data_out: tomo
      cutoff: 10.0
      minus_log: true
- httomolib.recon.algorithm:
    reconstruct_tomopy:
      data_in: tomo
      data_out: tomo
      center: null
      algorithm: FBP_CUDA
```
with the data `/dls/i12/data/2022/nt33730-1/rawdata/119647.nxs` that CUDA out of memory errors were occurring in the recon method, but that swapping the centering normalisation to reduce the number of reslices from 3 down to 1 somehow gets rid of the out of memory  error.

After seeing this behaviour, some rudimentary observation of the output of `nvidia-smi -l 1` and also printing the result of
```python
cupy.get_default_memory_pool().used_bytes()
```
in the code revealed that the two GPU processes in that MPI run indeed had "balanced memory" prior to the reslice, but as soon as the reslice occurred and the memory associated with each of the two GPU processes quickly became "unbalanced" when considering the fact that they are working with somewhat similar sizes of data.

For example, when the centering and normalisation methods are in the correct order:
- the reslice happens when centering needs to be done
- and no reslice occurs before normalisation

and here is the output of the printing of the used bytes, and one can see that when printing in the normalisation method, the used bytes between the two GPU processes are pretty even, but in the recon it has changed drastically to have one GPU process with far more bytes used/allocated than the other
```
(base) [twi18192@pc0074 HTTomo (improve-loader-params)]$ mpirun -n 2 python -m httomo /dls/i12/data/2022/nt33730-1/rawdata/119647.nxs test_pipeline_configs/i12-data.yaml outdata/ task_runner
Running task 1 (pattern=projection): standard_tomo...
The full dataset shape is (1871, 2160, 2560)
[1] Pad values are (0, 0).
/dls/i12/data/2022/nt33730-1/rawdata/119647.nxs
entry1/tomo_entry/data/data
70:1871, 900:905:, :
[0] Pad values are (0, 0).
/dls/i12/data/2022/nt33730-1/rawdata/119647.nxs
entry1/tomo_entry/data/data
70:1871, 900:905:, :
[1] Data shape is (901, 5, 2560) of type uint16
[0] Data shape is (900, 5, 2560) of type uint16
Running task 2 (pattern=projection): normalize_cupy...
Used bytes is 71142400
Used bytes is 71065600
normalize_cupy
normalize_cupy
Running task 3 (pattern=sinogram): find_center_vo_cupy...
<-------Reslicing/rechunking the data-------->
outdata/03-02-2023_18_21_24_output/intermediate.h5
/data
:,:,:
outdata/03-02-2023_18_21_24_output/intermediate.h5
/data
:,:,:
find_center_vo_cupy
The center of rotation is 1253.75
find_center_vo_cupy
Running task 4 (pattern=sinogram): reconstruct_tomopy...
Data shape is (1801, 3, 2560)
Used bytes is 147537920
Data shape is (1801, 2, 2560)
Used bytes is 36884480
reconstruct_tomopy
Saving intermediate file: 4-httomolib-reconstruct_tomopy-tomo-FBP_CUDA.h5
reconstruct_tomopy
Total number of reslices: 1
```
Note that _before_ the reslice, when running normalisation, the memory of the two GPU processes are:
- Process 1 = 71142400 bytes ~ 70MB
- Process 2 = 71065600 bytes ~ 70MB

which is pretty balanced, but _after_ the reslice, when running recon, the memory of the two GPU processes are:
- Process 1 = 147537920 bytes ~ 140MB
- Process 2 = 36884480 bytes = 35MB

which is now quite unbalanced. When going through the same observations with the pipeline that performs 3 reslices, it seems that the more reslices there are the larger the imbalance?

Watching the output of `nvidia-smi -l 1` also agreed with this observation of an "imbalance" between the two GPU processes' memory after a reslice.
