### ISSUE TITLE
Data saver to operate with metadata

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#50]
I thought would it be useful to have an explicit data saver module with an associated YAML template?
The main reason is to be able to operate with the metadata in hdf5 or nexus files, i.e. copy, rename, delete, etc. 
Here is an example: 
- input data file with a separate nexus
- needs to be loaded, downsampled and saved
- metadata from the nexus file should be passed to the modified hdf5 file
- potentially a path to the data could be also changed

So I'm thinking about the YAML template of the following structure: 
```yaml
- httomo.data.hdf.savers:
     hdf5_saver:
      data_in: input_data_name
      copy_metadata: True
      path_to_data: None
      ...
```
So this saver with copy the metadata from data_in and will not change the path to the data. 
Related [issue](https://github.com/DiamondLightSource/httomo/issues/12)
