### ISSUE TITLE
Patterns for methods

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#61]
We need to assign patterns to the methods rather than to  [wrappers](https://github.com/DiamondLightSource/httomo/blob/f2a9cc0af22d3dbcedde1beb56e92f39a411f31c/wrappers/httomolib/misc.py#L9). 
As we've got _tomopy_ and _httomolib_ libraries, both should be covered. 

Potentially all patterns could be stored in a separate text file (e.g. patterns.txt) with the following simple structure:
```
median_filter3d - all
stripe_removal - sinogram
...
```
The pattern will be extracted from the file, when the job runs. The advantage of this approach is that the patterns are all stored in one place.

**Comment by yousefmoazzam** [comment]
Here's some initial thoughts about this.

There are two options at the moment for the format of the file containing the pattern information for all methods: plain text, or YAML.

Here is a dummy example of the same information described in both plain text (as a table) and YAML (as a nested mapping), along with some pros and cons of each approach:

YAML
```yaml
prep:
  phase:
    retrieve_phase:
      pattern: sinogram
      pad: 5
  normalize:
    minus_log:
      pattern: projection
      pad: 3
    normalize:
      pattern: projection
      pad: 10
recon:
  algorithm:
    recon:
      pattern: sinogram
      pad: 0
  rotation:
    find_center_vo:
      pattern: sinogram
      pad: 0
```

YAML pros
- you can easily find the exact method you want by walking through the dict structure
- YAML is generally nicer to parse than strings, we already have YAML module/package in httomo as a dependency to do this

YAML cons
- you are forced to duplicate the keys in each entry, ie, every method has `pattern` and `pad` in it, which takes up some visual space


Plain text
```txt
method                        pattern               pad

prep.phase.retrieve_phase     projection            5
prep.normalize.minus_log      projection            3
prep.normalize.normalize      projection            10
recon.algorithm.recon         sinogram              0
recon.rotation.find_center_vo sinogram              0
```

Plain text pros
- the use of a table doesn't involve the duplication of `pattern` and `pad` as did the YAML case

Plain text cons
- writing entries in it is more tedious (dealing with inserting tabs, making sure the columns are nicely aligned, etc)
- locating the method you want to query information about requires parsing the text in the first column; ie, you must _search_ for the method unlike in the YAML case where you use the mapping structures to walk down to the desired method
- probably would like to interpret as a "table" data structure than to parse each line manually, so would need to add `pandas` or something similar as a dependency

Feel free to chime in with other pros/cons that come to mind!
