### ISSUE TITLE
Darks and flats are duplicated in MPI runs

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#68]
Running the following pipeline:
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: /entry1/tomo_entry/data/data
      image_key_path: /entry1/tomo_entry/instrument/detector/image_key
      dimension: 1
      pad: 0
- httomolib.misc.corr:
    remove_outlier3d_cupy:
      data_in_multi: [tomo, flats, darks]
      data_out_multi: [tomo, flats, darks]
      kernel_size: 3
      dif: 0.1
```

with two MPI processes on `tomo_standard.nxs` using the `--save_all` flag shows that:
- the projections have the correct dimension `(180, 128, 160)`
- the darks have an _incorrect_ dimension `(40, 128, 160)`, where indices 20 - 39 are duplicates of 0 - 19 (ie, 20 is the same as 0, 21 is the same as 1, etc.)
- the flats also have an _incorrect_ dimension `(40, 128, 160)`, with the same duplication as seen for the darks

It would first seem possible that the functionality for multiple input/output datasets is the cause of the bug, However, note that the projections have the correct dimension, in contrast to the darks/flats. This leads me to suspect that the issue could at least be partially related to how darks/flats are handled in MPI runs.
