### ISSUE TITLE
Add commented-out lines in autogenerated tomopy YAML template files

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#9]
Very minor, but autogenerated YAML templates for tomopy functions that are intended to have a commented-out line (to indicate that additional parameters are available in the wrapped tomopy function) currently have the comment wrapped inside a string like so:
```
- tomopy.recon.algorithm:
    recon:
      data_in: tomo
      data_out: tomo
      center: None
      sinogram_order: 'False'
      algorithm: None
      init_recon: None
      '#additional parameters': AVAILABLE
```
whereas it's intended to be something like

```
- tomopy.recon.algorithm:
    recon:
      data_in: tomo
      data_out: tomo
      center: None
      sinogram_order: 'False'
      algorithm: None
      init_recon: None
      #additional parameters: AVAILABLE
```

The former causes the given function to fail, as the string `#additional paramaters` is interpreted as a parameter name, which is incorrect.

This has only a minor impact on the documentation that will be produced in the future which users will copy+paste from in order to build their processing pipeline / user config YAML file.
